### ISSUE TITLE
First Install

### ISSUE THREAD

**Issue by faustinotv** [alicangnll/iptv-server#1]
which operating system and which version of php is needed to work?

**Comment by alicangnll** [comment]
You can use with PHP 7.2 and Windows / Linux (We are prefer Windows).

**Comment by alicangnll** [comment]
![0C19AD6D-C5A7-45BD-97A0-7869F04BDD8A](https://user-images.githubusercontent.com/23417905/112722746-49815100-8f1c-11eb-8dcf-aa4ea7cc3dd1.jpeg)
We are using CentOS and PHP 7.2

**Comment by alicangnll** [comment]
install.php updated.

Thanks for reply ))
